{{- if .Values.awscontroller.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: aws-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    {{- if .Values.awscontroller.cert.enabled }}
    alb.ingress.kubernetes.io/certificate-arn: {{.Values.awscontroller.cert.arn}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  {{- end}}
spec:
  {{- if .Values.awscontroller.cert.enabled }}
  tls:
    - hosts:
        {{-  range $host := .Values.awscontroller.cert.hosts }}
        - {{ $host }}
        {{- end }}
  {{- end }}
  rules:
      - http:
          paths:
            - path: /api/v1/integrations
              pathType: Prefix
              backend:
                service:
                  name: {{ include "thingsboard.integrationexecutor.label" . }}
                  port:
                    number: 8080
            - path: /api/v1/
              pathType: Prefix
              backend:
                service:
                  name: {{ include "thingsboard.ts.host" . }}
                  port:
                    number: 8080
            - path: /static/rulenode/
              pathType: Prefix
              backend:
                service:
                  name: {{ include "thingsboard.node.host" . }}
                  port:
                    number: 8080
            - path: /static/
              pathType: Prefix
              backend:
                service:
                  name: {{ include "thingsboard.web.host" . }}
                  port:
                    number: 8080
            - path: /index.html
              pathType: Prefix
              backend:
                service:
                  name: {{ include "thingsboard.web.host" . }}
                  port:
                    number: 8080
            - path: /api
              pathType: Prefix
              backend:
                service:
                  name: {{ include "thingsboard.node.host" . }}
                  port:
                    number: 8080
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ include "thingsboard.web.host" . }}
                  port:
                    number: 8080
{{- end }}