{{- if .Values.defaultIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/integrations/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.ts.host" . }}
                port:
                  number: 8080
          - path: /static/rulenode/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /static/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
{{- end}}