{{- if .Values.defaultIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.defaultIngress.name | default "http-ingress" }}
  {{- with .Values.defaultIngress.labels }}
    labels:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.defaultIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.defaultIngress.ingressClassName }}
  ingressClassName: {{ .Values.defaultIngress.ingressClassName }}
  {{- end }}
  {{- if .Values.defaultIngress.tls }}
  tls:
    {{- range .Values.defaultIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.defaultIngress.hosts }}
    {{- range .Values.defaultIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api/v1/integrations/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.node.host" $ }}
                port:
                  number: 8080
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.ts.host" $ }}
                port:
                  number: 8080
          - path: /static/rulenode/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" $ }}
                port:
                  number: 8080
          - path: /static/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" $ }}
                port:
                  number: 8080
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" $ }}
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" $ }}
                port:
                  number: 8080
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" $ }}
                port:
                  number: 8080
    {{- end }}
    {{- else }}
    - http:
        paths:
          - path: /api/v1/integrations/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.ts.host" . }}
                port:
                  number: 8080
          - path: /static/rulenode/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /static/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
    {{- end }}
{{- end }}
