{{- $namespace := .Release.Namespace -}}
{{ $releaseName := .Release.Name }}
 {{- range $key, $transport := .Values.transports }}
{{- if $transport.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{$transport.name}}-loadbalancer
  namespace: {{$namespace}}
  {{- with $transport.service.annotations }}
  annotations:
      {{- toYaml $transport.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: {{ ternary (printf "%s-%s" $releaseName $transport.name ) (include "thingsboard.node.label" $) $.Values.installation.msa }}
  ports:
    {{- range $transport.ports }}
    - port: {{ .value }}
      targetPort: {{ .value }}
      name: {{ .name }}
      protocol: {{ .protocol | default "TCP" | toString }}
    {{- end }}
 {{- end}}
{{- end}}

