{{- if  .Values.azure.loadbalancer.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: aks-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    {{- if .Values.azure.loadbalancer.cert.enabled  }}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
  {{- end}}
spec:
  {{- if .Values.azure.loadbalancer.cert.enabled }}
  tls:
    - secretName: {{ .Values.azure.loadbalancer.cert.certSecret }}
      {{- if .Values.azure.loadbalancer.cert.hosts }}
      hosts:
        {{-  range $host := .Values.azure.loadbalancer.cert.hosts }}
        - {{ $host }}
        {{- end }}
      {{- end }}
  {{- end }}
  {{- if and .Values.azure.loadbalancer.cert.hosts }}
  rules:
    {{- range $host := .Values.azure.loadbalancer.cert.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /api/v1/integrations/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.node.host" $ }}
                port:
                  number: 8080
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.ts.host" $ }}
                port:
                  number: 8080
          - path: /static/rulenode/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" $ }}
                port:
                  number: 8080
          - path: /static/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.web.host" $ }}
                port:
                  number: 8080
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" $ }}
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" $ }}
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.web.host" $ }}
                port:
                  number: 8080
    {{- end }}
  {{- else }}
  rules:
    - http:
        paths:
          - path: /api/v1/integrations/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.ts.host" . }}
                port:
                  number: 8080
          - path: /static/rulenode/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /static/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
  {{- end }}
{{- end -}}