{{- $namespace := .Release.Namespace -}}
  {{- $releaseName := .Release.Name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$releaseName}}-node-custom-env
  namespace: {{ $namespace }}
  labels:
    name: {{$releaseName}}-node-custom-env
data:
  {{- range $key, $val := .Values.node.customEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}