{{- $namespace := .Release.Namespace -}}
  {{- if .Values.installation.pe }}
apiVersion: v1
kind: Secret
metadata:
  name: tb-license
  namespace: {{$namespace}}
type: Opaque
stringData:
  license-key: {{ .Values.installation.licenseKey }}
  {{- end }}
