{{- $appVersion := .Chart.AppVersion -}}
{{- $namespace := .Release.Namespace -}}
{{- $releaseName := .Release.Name }}
{{- if and .Values.installation.msa .Values.versionControl.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thingsboard.versioncontrol.label" . }}
  namespace: {{ $namespace }}
  annotations:
  {{- .Values.versionControl.statefulSet.annotations | toYaml | nindent 4}}
  labels:
    app: {{ include "thingsboard.versioncontrol.label" . }}
spec:
  serviceName: {{ include "thingsboard.versioncontrol.label" . }}
  replicas: {{ .Values.versionControl.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ include "thingsboard.versioncontrol.label" . }}
  template:
    metadata:
      annotations:
      {{- .Values.versionControl.annotations | toYaml | nindent 8}}
      labels:
        app: {{ include "thingsboard.versioncontrol.label" . }}
    spec:
      nodeSelector:
        {{- .Values.versionControl.nodeSelector | toYaml | nindent 8 }}
      affinity:
        {{- .Values.versionControl.affinity | toYaml | nindent 8 }}
      securityContext:
        {{- .Values.versionControl.securityContext | toYaml | nindent 8 }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      containers:
        - name: server
          imagePullPolicy: {{ .Values.versionControl.imagePullPolicy }}
          image: {{ include "thingsboard.versioncontrol.image" . }}
          ports:
            {{- range .Values.versionControl.ports }}
            - containerPort: {{ .value }}
              name: {{ .name }}
              protocol: {{ .protocol | default "TCP" | toString }}
            {{- end}}
          env:
            - name: TB_SERVICE_TYPE
              value: "tb-vc-executor"
            - name: RPC_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TB_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TB_HOST
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WEB_APPLICATION_ENABLE
              value: "true"
            - name: WEB_APPLICATION_TYPE
              value: "servlet"
            - name: HTTP_BIND_ADDRESS
              value: "0.0.0.0"
            - name: HTTP_BIND_PORT
              value: "8080"
            {{- range $envKey, $envValue := .Values.versionControl.customEnv }}
            - name: {{ $envKey }}
              value: {{ $envValue | quote }}
            {{- end }}
          envFrom:
            {{- include "thingboard.coordinator.configuration.ref" . | indent 12 }}
            {{- include "thingboard.queue.configuration.ref" . | indent 12 }}
            {{- include "thingboard.cache.configuration.ref" . | indent 12 }}
            {{- include "thingboard.cassandra.configuration.ref" . | indent 12 }}
            {{- include "thingboard.postgres.configuration.ref" . | indent 12 }}
          readinessProbe:
            {{- .Values.versionControl.readinessProbe | toYaml | nindent 12 }}
          livenessProbe:
            {{- .Values.versionControl.livenessProbe | toYaml | nindent 12 }}
          resources:
            {{- .Values.versionControl.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: {{ printf "%s-version-control-config" $releaseName}}
              mountPath: /config/tb-vc-executor.conf
              subPath: tb-vc-executor.conf
            - name: {{ printf "%s-version-control-logback-config" $releaseName}}
              mountPath: /config/logback.xml
              subPath: logback.xml
            - name: {{$releaseName}}-version-control-logs
              mountPath: /var/log/thingsboard
            - name: {{$releaseName}}-version-control-data
              mountPath: /data
              readOnly: false
      restartPolicy: {{ .Values.node.restartPolicy }}
      volumes:
        - name: {{ printf "%s-version-control-config" $releaseName}}
          configMap:
            name: {{ ternary (printf "%s-version-control-default-config" $releaseName) .Values.versionControl.existingTBConfigConfigMap  (empty .Values.versionControl.existingTBConfigConfigMap) }}
            items:
              - key: conf
                path: tb-vc-executor.conf
        - name: {{ printf "%s-version-control-logback-config" $releaseName}}
          configMap:
            name: {{ ternary (printf "%s-version-control-default-logback-config" $releaseName) .Values.versionControl.existingTBLogbackConfigMap  (empty .Values.versionControl.existingTBLogbackConfigMap) }}
            items:
              - key: logback
                path: logback.xml
        - name: {{ $releaseName }}-version-control-logs
          emptyDir: {}
        {{- if not .Values.versionControl.persistence.enabled }}
        - name: {{ printf "%s-version-control-data" $releaseName}}
          emptyDir: {}
        {{- else if .Values.versionControl.persistence.existingClaim }}
        - name: {{ printf "%s-version-control-data" $releaseName}}
          persistentVolumeClaim:
            claimName: {{ .Values.versionControl.persistence.existingClaim }}
        {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: {{ printf "%s-version-control-data" $releaseName}}
      spec:
        accessModes: {{ .Values.versionControl.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.engine.persistence.size }}
        storageClassName: {{ ternary "" .Values.versionControl.persistence.storageClass (empty .Values.versionControl.persistence.storageClass) }}
        {{- end }}
{{- end}}
