{{- $existingSecret := include "thingsboard.existingSecrets" . | fromYaml | default dict }}
{{- if not (hasKey $existingSecret "SPRING_DATASOURCE_PASSWORD") }}
{{- $namespace := .Release.Namespace -}}
  {{- $releaseName := .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{$releaseName}}-postgres-secret
  namespace: {{$namespace}}
type: Opaque
data:
  {{- if .Values.internalPostgresql.enabled }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.internalPostgresql.auth.password | b64enc }}
  {{- else }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.externalPostgresql.password | b64enc }}
  {{- end }}
{{- end }}
