{{- if .Values.gcloud.loadBalancer.enabled -}}
{{- if .Values.gcloud.loadBalancer.cert.enabled -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    {{-  range $host := .Values.gcloud.loadBalancer.cert.hosts }}
    - {{ $host }}
    {{- end }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: thingsboard-http-fe-config
spec:
  redirectToHttps:
    enabled: true
---
  {{- end -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: gke-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    {{- if .Values.gcloud.loadBalancer.staticAddressName }}
    kubernetes.io/ingress.global-static-ip-name: thingsboard-http-lb-address
    {{- end }}
  {{- if .Values.gcloud.loadBalancer.cert.enabled }}
    networking.gke.io/managed-certificates: managed-cert
    networking.gke.io/v1beta1.FrontendConfig: thingsboard-http-fe-config
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/integrations/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.ts.host" . }}
                port:
                  number: 8080
          - path: /static/rulenode/
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
          - path: /static/
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.web.host" . }}
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "thingsboard.node.host" . }}
                port:
                  number: 8080
  {{- end -}}